### ISSUE TITLE
Chiseled bookcase is missing a recipe

### ISSUE THREAD

**Issue by moonracer3000** [GabrielDja/Trick_Update_1.20#3]
Just testing v1.5 and the chiseled bookcase is in the game but there doesn't appear to be a crafting recipe for it so you can only get it through cheats. Also the block always displays a full set of books.

**Comment by GabrielDja** [comment]
Hi moonracer3000!
Thanks for pointing this out, the craft will be added in v1.6! However for the textures of the books on the Chiseled Bookshelf I don't promise anything for it to be perfect... (And there is no date for it to be added)
